name: snozzy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+4

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.1
  hive_flutter: ^1.0.0
  hive_generator: ^1.1.2
  receive_sharing_intent: ^1.4.5
  string_validator: ^0.3.0
  metadata_fetch: ^0.4.1
  mime: ^1.0.0
  date_time_picker: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  awesome_notifications: ^0.6.21
  video_player: ^2.1.0
  flick_video_player: ^0.3.1
  flutter_inappwebview: ^5.3.0
  url_launcher: ^6.0.3
  firebase_core: ^1.0.2
  admob_flutter: ^2.0.0
  firebase_analytics: ^9.1.5
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.0
  open_file: ^3.0.3
  share: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  file_picker: ^4.5.1
  flutter_countdown_timer: ^4.0.2
  fluttertoast: ^8.0.3
  flutter_picker: ^2.0.1
  in_app_review: ^2.0.2
  font_awesome_flutter: ^10.1.0
  firebase_crashlytics: ^2.0.4
  uuid: ^3.0.6

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/res_icon.png"
  image_path_android: "assets/icon/res_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.9

flutter:

  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/icon/res_icon.png
    - android/app/src/main/res/drawable/res_notification_icon.png